spring:
  application:
    name: SpringConfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CaptainSuf/config.git
          #uri: git@github.com:CaptainSuf/config.git
          search-paths: /{application}
          username:
          password:
          #ignore-local-ssh-settings: true
          #private-key:

# 配置注册中心
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:18090/eureka/

server:
  port: 5001

encrypt:
  key: undifinded
